version: '3.1'

services:
  db-test:
    container_name: db-test
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .env.test
    restart: unless-stopped

  api-test:
    container_name: api-test
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    command: yarn start:debug
    ports:
      - 3001:3000
    environment:
      NODE_ENV: test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-test
    restart: unless-stopped
volumes:
  postgres-data-test:
